name: l1-rnaseq-pipeline
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python>=3.8,<3.12
  - fastqc>=0.11.9
  - bowtie=1.3.1
  - samtools>=1.10
  - bedtools>=2.29.0
  - subread>=2.0.0